/**
 * Shyft Auto
 * An api to run the client and administration of the shyft auto app.
 *
 * OpenAPI spec version: 0.2.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import * as models from './models';

export interface UserProfileModel {
    id?: string;

    first_name?: string;

    last_name?: string;

    date_joined?: string;

    image?: string;

    /**
     * Role:  * Driver - Drives a fleet car or a customer car to/from the dealership and customer location  * Admin - Manages customer tickets  * Customer - Uses the mobile app to book and pay for  appointments 
     */
    role?: UserProfileModel.RoleEnum;

}
export namespace UserProfileModel {
    export enum RoleEnum {
        Driver = <any> 'Driver',
        Admin = <any> 'Admin',
        Customer = <any> 'Customer'
    }
}
